# Generated by Django 6.1 on 2026-09-04 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
