# Generated by Django 6.1 on 2026-09-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_exam_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='puntaje',
            field=models.IntegerField(default=10),
        ),
    ]
